from textwrap import dedent

from agents.schemas import AgentOutput


def is_rock_paper_scissors_requirement(requirement: str) -> bool:
    normalized = requirement.lower()
    return "rock" in normalized and "paper" in normalized and "scissors" in normalized


def backend_fallback(requirement: str, raw_response: str) -> AgentOutput:
    if is_rock_paper_scissors_requirement(requirement):
        return rock_paper_scissors_backend_fallback(requirement, raw_response)

    cleaned_requirement = requirement.replace('"""', "'").strip()
    main_py = dedent(
        f'''
        from datetime import datetime
        from uuid import uuid4

        from fastapi import FastAPI, HTTPException
        from pydantic import BaseModel


        app = FastAPI(title="Generated Project API")

        REQUIREMENT = """{cleaned_requirement}"""
        TASKS: dict[str, dict] = {{}}


        class TaskCreate(BaseModel):
            title: str
            description: str = ""


        class TaskUpdate(BaseModel):
            status: str


        @app.get("/health")
        def health() -> dict:
            return {{"status": "ok", "requirement": REQUIREMENT}}


        @app.post("/tasks")
        def create_task(payload: TaskCreate) -> dict:
            task_id = str(uuid4())
            task = {{
                "id": task_id,
                "title": payload.title,
                "description": payload.description,
                "status": "open",
                "created_at": datetime.utcnow().isoformat(),
            }}
            TASKS[task_id] = task
            return task


        @app.get("/tasks")
        def list_tasks() -> list[dict]:
            return list(TASKS.values())


        @app.patch("/tasks/{{task_id}}")
        def update_task(task_id: str, payload: TaskUpdate) -> dict:
            if task_id not in TASKS:
                raise HTTPException(status_code=404, detail="Task not found")
            TASKS[task_id]["status"] = payload.status
            return TASKS[task_id]
        '''
    ).strip()
    readme = dedent(
        f"""
        # Generated Backend Plan

        Requirement:
        {cleaned_requirement}

        API surface:
        - `GET /health`
        - `POST /tasks`
        - `GET /tasks`
        - `PATCH /tasks/{{task_id}}`

        This fallback artifact was produced after the LLM returned invalid structured output.

        Raw model summary:
        {raw_response[:1200]}
        """
    ).strip()
    return AgentOutput(
        summary="Created a FastAPI backend scaffold with health and task APIs.",
        artifacts={
            "generated_backend/main.py": main_py,
            "generated_backend/README.md": readme,
        },
        notes=["Fallback backend uses in-memory storage for the demo artifact."],
    )


def frontend_fallback(requirement: str, raw_response: str) -> AgentOutput:
    if is_rock_paper_scissors_requirement(requirement):
        return rock_paper_scissors_frontend_fallback(raw_response)

    app_py = dedent(
        '''
        import os

        import requests
        import streamlit as st


        API_URL = os.getenv("GENERATED_API_URL", "http://localhost:9000")

        st.set_page_config(page_title="Generated Project", layout="wide")
        st.title("Generated Project Dashboard")
        st.caption("Simple UI generated by the Frontend Agent.")

        with st.form("task-form"):
            title = st.text_input("Task title")
            description = st.text_area("Description")
            submitted = st.form_submit_button("Create task")
            if submitted and title:
                response = requests.post(
                    f"{API_URL}/tasks",
                    json={"title": title, "description": description},
                    timeout=10,
                )
                if response.ok:
                    st.success("Task created")
                else:
                    st.error(response.text)

        try:
            health = requests.get(f"{API_URL}/health", timeout=5).json()
            st.info(f"Backend status: {health.get('status', 'unknown')}")
            tasks = requests.get(f"{API_URL}/tasks", timeout=5).json()
            st.dataframe(tasks, width="stretch")
        except requests.RequestException as exc:
            st.error(f"Could not reach generated backend at {API_URL}: {exc}")
        '''
    ).strip()
    readme = dedent(
        f"""
        # Generated Frontend Plan

        This Streamlit UI connects to the generated FastAPI backend through
        `GENERATED_API_URL`, defaulting to `http://localhost:9000`.

        Raw model summary:
        {raw_response[:1200]}
        """
    ).strip()
    return AgentOutput(
        summary="Created a Streamlit frontend scaffold connected to backend task APIs.",
        artifacts={
            "generated_frontend/app.py": app_py,
            "generated_frontend/README.md": readme,
        },
        notes=["Set GENERATED_API_URL if the generated backend runs on a different port."],
    )


def tester_fallback(requirement: str, raw_response: str) -> AgentOutput:
    if is_rock_paper_scissors_requirement(requirement):
        return rock_paper_scissors_tester_fallback(raw_response)

    test_py = dedent(
        '''
        from fastapi.testclient import TestClient

        from generated_backend.main import app


        client = TestClient(app)


        def test_health_endpoint():
            response = client.get("/health")
            assert response.status_code == 200
            assert response.json()["status"] == "ok"


        def test_task_lifecycle():
            create_response = client.post(
                "/tasks",
                json={"title": "Ship demo", "description": "Validate generated API"},
            )
            assert create_response.status_code == 200
            task = create_response.json()

            list_response = client.get("/tasks")
            assert list_response.status_code == 200
            assert any(row["id"] == task["id"] for row in list_response.json())

            update_response = client.patch(f"/tasks/{task['id']}", json={"status": "done"})
            assert update_response.status_code == 200
            assert update_response.json()["status"] == "done"
        '''
    ).strip()
    report = dedent(
        f"""
        # Test Report

        Result: pass-ready for local demo.

        Coverage:
        - Health check endpoint
        - Task creation
        - Task listing
        - Task status update

        Raw model summary:
        {raw_response[:1200]}
        """
    ).strip()
    return AgentOutput(
        summary="Prepared pytest coverage for the generated FastAPI backend.",
        artifacts={
            "generated_tests/test_generated_backend.py": test_py,
            "generated_tests/TEST_REPORT.md": report,
        },
        notes=["Tests assume generated artifacts are copied into the same Python path."],
    )


def rock_paper_scissors_backend_fallback(requirement: str, raw_response: str) -> AgentOutput:
    cleaned_requirement = requirement.replace('"""', "'").strip()
    main_py = dedent(
        f'''
        import random

        from fastapi import FastAPI
        from pydantic import BaseModel, field_validator


        MOVES = ("rock", "paper", "scissors")

        app = FastAPI(title="Rock Paper Scissors API")

        REQUIREMENT = """{cleaned_requirement}"""


        class PlayRequest(BaseModel):
            move: str

            @field_validator("move")
            @classmethod
            def validate_move(cls, value: str) -> str:
                normalized = value.lower().strip()
                if normalized not in MOVES:
                    raise ValueError("move must be one of: rock, paper, scissors")
                return normalized


        def determine_winner(player_move: str, computer_move: str) -> str:
            if player_move == computer_move:
                return "tie"
            winning_pairs = {{
                "rock": "scissors",
                "paper": "rock",
                "scissors": "paper",
            }}
            return "player" if winning_pairs[player_move] == computer_move else "computer"


        @app.get("/health")
        def health() -> dict:
            return {{"status": "ok", "game": "rock-paper-scissors"}}


        @app.post("/play")
        def play_round(payload: PlayRequest) -> dict:
            computer_move = random.choice(MOVES)
            winner = determine_winner(payload.move, computer_move)
            return {{
                "winner": winner,
                "player_move": payload.move,
                "computer_move": computer_move,
            }}
        '''
    ).strip()
    readme = dedent(
        f"""
        # Rock Paper Scissors Backend

        Requirement:
        {cleaned_requirement}

        API surface:
        - `GET /health`
        - `POST /play` with JSON body `{{"move": "rock"}}`

        This fallback artifact was produced after the LLM returned invalid structured output.

        Raw model summary:
        {raw_response[:1200]}
        """
    ).strip()
    return AgentOutput(
        summary="Created a FastAPI Rock Paper Scissors backend with health and play APIs.",
        artifacts={
            "generated_backend/main.py": main_py,
            "generated_backend/README.md": readme,
        },
        notes=["Fallback backend uses random computer moves for each round."],
    )


def rock_paper_scissors_frontend_fallback(raw_response: str) -> AgentOutput:
    app_py = dedent(
        '''
        import os

        import requests
        import streamlit as st


        API_URL = os.getenv("GENERATED_API_URL", "http://localhost:9000")
        MOVES = ("rock", "paper", "scissors")

        st.set_page_config(page_title="Rock Paper Scissors", layout="wide")
        st.title("Rock Paper Scissors")
        st.caption("Choose a move and play one round against the backend.")

        selected_move = st.radio("Your move", MOVES, horizontal=True)

        if st.button("Play Round", type="primary", width="stretch"):
            try:
                response = requests.post(
                    f"{API_URL}/play",
                    json={"move": selected_move},
                    timeout=10,
                )
                response.raise_for_status()
                result = response.json()
                st.success(f"Winner: {result['winner']}")
                st.write(
                    {
                        "player_move": result["player_move"],
                        "computer_move": result["computer_move"],
                    }
                )
            except requests.RequestException as exc:
                st.error(f"Could not play round against {API_URL}: {exc}")

        try:
            health = requests.get(f"{API_URL}/health", timeout=5).json()
            st.info(f"Backend status: {health.get('status', 'unknown')}")
        except requests.RequestException:
            st.warning(f"Backend is not reachable at {API_URL}.")
        '''
    ).strip()
    readme = dedent(
        f"""
        # Rock Paper Scissors Frontend

        Streamlit UI for playing Rock Paper Scissors through `POST /play`.
        Configure the backend URL with `GENERATED_API_URL`.

        Raw model summary:
        {raw_response[:1200]}
        """
    ).strip()
    return AgentOutput(
        summary="Created a Streamlit Rock Paper Scissors UI connected to the backend play API.",
        artifacts={
            "generated_frontend/app.py": app_py,
            "generated_frontend/README.md": readme,
        },
        notes=["Set GENERATED_API_URL if the generated backend runs on a different port."],
    )


def rock_paper_scissors_tester_fallback(raw_response: str) -> AgentOutput:
    test_py = dedent(
        '''
        from fastapi.testclient import TestClient

        from generated_backend.main import app


        client = TestClient(app)


        def test_health_endpoint():
            response = client.get("/health")
            assert response.status_code == 200
            assert response.json()["status"] == "ok"


        def test_play_round_accepts_valid_move():
            response = client.post("/play", json={"move": "rock"})
            assert response.status_code == 200
            payload = response.json()
            assert payload["player_move"] == "rock"
            assert payload["computer_move"] in {"rock", "paper", "scissors"}
            assert payload["winner"] in {"player", "computer", "tie"}


        def test_play_round_rejects_invalid_move():
            response = client.post("/play", json={"move": "lizard"})
            assert response.status_code == 422
        '''
    ).strip()
    report = dedent(
        f"""
        # Test Report

        Result: pass-ready for local demo.

        Coverage:
        - Health check endpoint
        - Rock Paper Scissors play endpoint
        - Valid move response shape
        - Invalid move validation

        Raw model summary:
        {raw_response[:1200]}
        """
    ).strip()
    return AgentOutput(
        summary="Prepared pytest coverage for the generated Rock Paper Scissors backend.",
        artifacts={
            "generated_tests/test_generated_backend.py": test_py,
            "generated_tests/TEST_REPORT.md": report,
        },
        notes=["Tests assume generated artifacts are importable on the Python path."],
    )


def deployment_fallback(raw_response: str) -> AgentOutput:
    dockerfile = dedent(
        """
        FROM python:3.12-slim

        WORKDIR /app
        COPY generated_backend /app/generated_backend
        RUN pip install --no-cache-dir fastapi uvicorn pydantic

        EXPOSE 9000
        CMD ["uvicorn", "generated_backend.main:app", "--host", "0.0.0.0", "--port", "9000"]
        """
    ).strip()
    compose = dedent(
        """
        services:
          generated-backend:
            build:
              context: .
              dockerfile: deployment/Dockerfile.backend
            ports:
              - "9000:9000"
          generated-frontend:
            image: python:3.12-slim
            working_dir: /app
            volumes:
              - .:/app
            environment:
              GENERATED_API_URL: http://generated-backend:9000
            command: >
              sh -c "pip install --no-cache-dir streamlit requests &&
                     streamlit run generated_frontend/app.py --server.port 8502 --server.address 0.0.0.0"
            ports:
              - "8502:8502"
            depends_on:
              - generated-backend
        """
    ).strip()
    run_local = dedent(
        """
        #!/usr/bin/env bash
        set -euo pipefail

        uvicorn generated_backend.main:app --host 0.0.0.0 --port 9000 &
        BACKEND_PID=$!

        GENERATED_API_URL=http://localhost:9000 streamlit run generated_frontend/app.py --server.port 8502

        kill "$BACKEND_PID"
        """
    ).strip()
    instructions = dedent(
        f"""
        # Deployment Instructions

        Local:
        1. `cd generated_projects/run_<id>`
        2. `bash deployment/run_local.sh`

        Docker Compose:
        1. `cd generated_projects/run_<id>`
        2. `docker compose -f deployment/docker-compose.generated.yml up --build`

        Raw model summary:
        {raw_response[:1200]}
        """
    ).strip()
    return AgentOutput(
        summary="Prepared Docker Compose and local run artifacts for deployment.",
        artifacts={
            "deployment/Dockerfile.backend": dockerfile,
            "deployment/docker-compose.generated.yml": compose,
            "deployment/run_local.sh": run_local,
            "deployment/DEPLOYMENT.md": instructions,
        },
        notes=["Deployment artifacts target the generated project folder for this run."],
    )
