from textwrap import dedent

from agents.base import AgentContext, AgentResult, BaseAgent


class FrontendAgent(BaseAgent):
    name = "Frontend Agent"
    role = "Frontend Engineer"

    def task_instructions(self) -> str:
        return (
            "Create UI/dashboard code that calls the generated backend APIs. "
            "Prefer a simple Streamlit implementation for the local demo."
        )

    def fallback_output(self, context: AgentContext, raw_response: str) -> AgentResult:
        app_py = dedent(
            '''
            import os

            import requests
            import streamlit as st


            API_URL = os.getenv("GENERATED_API_URL", "http://localhost:9000")

            st.set_page_config(page_title="Generated Project", layout="wide")
            st.title("Generated Project Dashboard")
            st.caption("Simple UI generated by the Frontend Agent.")

            with st.form("task-form"):
                title = st.text_input("Task title")
                description = st.text_area("Description")
                submitted = st.form_submit_button("Create task")
                if submitted and title:
                    response = requests.post(
                        f"{API_URL}/tasks",
                        json={"title": title, "description": description},
                        timeout=10,
                    )
                    if response.ok:
                        st.success("Task created")
                    else:
                        st.error(response.text)

            try:
                health = requests.get(f"{API_URL}/health", timeout=5).json()
                st.info(f"Backend status: {health.get('status', 'unknown')}")
                tasks = requests.get(f"{API_URL}/tasks", timeout=5).json()
                st.dataframe(tasks, use_container_width=True)
            except requests.RequestException as exc:
                st.error(f"Could not reach generated backend at {API_URL}: {exc}")
            '''
        ).strip()
        readme = dedent(
            f"""
            # Generated Frontend Plan

            This Streamlit UI connects to the generated FastAPI backend through
            `GENERATED_API_URL`, defaulting to `http://localhost:9000`.

            Raw model summary:
            {raw_response[:1200]}
            """
        ).strip()
        return AgentResult(
            summary="Created a Streamlit frontend scaffold connected to backend task APIs.",
            artifacts={
                "generated_frontend/app.py": app_py,
                "generated_frontend/README.md": readme,
            },
            notes=["Set GENERATED_API_URL if the generated backend runs on a different port."],
        )

